# Generated by Django 3.1.7 on 2021-03-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='user_image',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='image_url',
            new_name='user_image_url',
        ),
    ]
