# Generated by Django 3.1.7 on 2021-03-20 11:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_auto_20210320_0717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Posts',
        ),
    ]
