# Generated by Django 3.1.7 on 2021-03-21 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('forum', '0003_auto_20210320_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.userprofile'),
        ),
    ]
