# Generated by Django 3.1.7 on 2021-03-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20210321_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
