# Generated by Django 3.1.7 on 2021-03-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210309_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='original_order',
            new_name='original_bag',
        ),
    ]
