# Generated by Django 3.1.7 on 2021-03-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='UserProfile',
            new_name='user_profile',
        ),
    ]
