# Generated by Django 3.1.7 on 2021-03-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('products', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.userprofile'),
        ),
    ]
