# Generated by Django 3.1.7 on 2021-03-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('products', '0004_auto_20210322_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='profiles.userprofile'),
        ),
    ]
