# Generated by Django 3.1.7 on 2021-03-22 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('products', '0005_auto_20210322_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owned_by',
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.userprofile'),
        ),
    ]
