# Generated by Django 3.1.7 on 2021-03-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210322_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='created_by',
        ),
    ]
